name: Keep Render Server Alive

on:
  schedule:
    - cron: "*/15 * * * *" # Runs every 15 minutes
  workflow_dispatch: # Optional manual trigger - It lets you manually trigger the workflow from the GitHub Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the /ping route
        run: |
          curl -I https://blognest-2sbr.onrender.com/ping || exit 1
